openapi: 3.0.0
info:
  version: 0.2.0
  title: URL Shortener API
  description: A sample API of service which can shorten URLs
servers:
  - url: http://localhost:8080
paths:
  /:
    post:
      summary: Create shortened URL for send data
      description: Receive data, build for it short URL and send in response
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: https://practicum.yandex.kz/
      responses:
        '201':
          description: Short URL successfully created
          content:
            text/plain:
              schema:
                type: string
                example: http://localhost:8080/2a49568d
        '400':
          description: Bad request
        '409':
          description: Such URL already saved in system
          content:
            text/plain:
              schema:
                type: string
                example: http://localhost:8080/2a49568d
  /{shortenedUrlUUID}:
    get:
      summary: Process shortened URL to original one propose
      description: Seek in Storage record with UUID `shortenedUrlUUID` and redirect to original URL
      parameters:
        - in: path
          name: shortenedUrlUUID
          schema:
            type: string
          required: true
      responses:
        '307':
          description: Redirected to original URL
        '400':
          description: Bad request
  /api/shorten:
    post:
      summary: Create shortened URL for send data
      description: Receive data, build for it short URL and send in response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: https://practicum.yandex.kz/
      responses:
        '201':
          description: Short URL successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: http://localhost:8080/2a49568d
        '400':
          description: Bad request
        '409':
          description: Such URL already saved in system
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: http://localhost:8080/2a49568d

  /ping:
    get:
      summary: Allows to check if DB connected correctly
      description: Make PingContex for DB DSN
      responses:
        '200':
          description: Everything is fine
        '500':
          description: Can not establish connection with DB
  /api/shorten/batch:
    post:
      summary: Create shortened URL for list of send urls
      description: Make shortening and save to storage each URL from list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  correlation_id:
                    type: string
                    example: aef12d
                  original_url:
                    type: string
                    example: https://practicum.yandex.kz/
      responses:
        '201':
          description: Short URLs successfully created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    correlation_id:
                      type: string
                      example: aef12d
                    short_url:
                      type: string
                      example: http://localhost:8080/2a49568d
        '400':
          description: Bad request