// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/paulbahush/projects/yp/url-shortener/internal/storage/storage.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/PaBah/url-shortener.git/internal/models"
	"go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AsyncCheckURLsUserID mocks base method.
func (m *MockRepository) AsyncCheckURLsUserID(usedID string, shortURL chan string) chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsyncCheckURLsUserID", usedID, shortURL)
	ret0, _ := ret[0].(chan string)
	return ret0
}

// AsyncCheckURLsUserID indicates an expected call of AsyncCheckURLsUserID.
func (mr *MockRepositoryMockRecorder) AsyncCheckURLsUserID(usedID, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncCheckURLsUserID", reflect.TypeOf((*MockRepository)(nil).AsyncCheckURLsUserID), usedID, shortURL)
}

// DeleteShortURLs mocks base method.
func (m *MockRepository) DeleteShortURLs(ctx context.Context, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShortURLs", ctx, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShortURLs indicates an expected call of DeleteShortURLs.
func (mr *MockRepositoryMockRecorder) DeleteShortURLs(ctx, shortURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShortURLs", reflect.TypeOf((*MockRepository)(nil).DeleteShortURLs), ctx, shortURLs)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, ID string) (models.ShortenURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, ID)
	ret0, _ := ret[0].(models.ShortenURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, ID)
}

// GetAllUsers mocks base method.
func (m *MockRepository) GetAllUsers(ctx context.Context) ([]models.ShortenURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].([]models.ShortenURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockRepositoryMockRecorder) GetAllUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockRepository)(nil).GetAllUsers), ctx)
}

// Store mocks base method.
func (m *MockRepository) Store(ctx context.Context, shortURL models.ShortenURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, shortURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRepositoryMockRecorder) Store(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRepository)(nil).Store), ctx, shortURL)
}

// StoreBatch mocks base method.
func (m *MockRepository) StoreBatch(ctx context.Context, shortURLsMap map[string]models.ShortenURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBatch", ctx, shortURLsMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBatch indicates an expected call of StoreBatch.
func (mr *MockRepositoryMockRecorder) StoreBatch(ctx, shortURLsMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBatch", reflect.TypeOf((*MockRepository)(nil).StoreBatch), ctx, shortURLsMap)
}
