name: codecov

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codecovtest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: PaBah/url-shortener
      
